# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386278d35953e00b6212ec2725ce7bd1473a4d9b313101afd33b4728a9267930a03be234d44472610725eb855bf3f3bb7b4e72e3097d75675caa571301a14014

test:
  secret_key_base: 2c0996a9b9e95562b840acff289552ecda3ab5dadda4e869ab5236436805bbdb16f5e60f427059a53cea03aa9057845d6242621a37dd01a73bafb625bb96cbc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
